[package]
name = "switchboard-function"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = "^1"
futures = "0.3"
switchboard-evm = "0.2.0"
switchboard-utils = "0.6"
ethers = { version = "2.0.3", features = [ "ws", "rustls" ] }
